name: Continuous Delivery

on:
  push:
    tags:
      - '*'

env:
  TARGET_IP: ${{ vars.TARGET_IP }}

jobs:
  deploy:
    name: Deploy and Verify
    runs-on: self-hosted

    steps:
      - name: Deploy application to Target Node
        run: |
          ssh -o StrictHostKeyChecking=no vagrant@${TARGET_IP} "sudo systemctl restart nestjs-app.service"

      - name: Verify application status
        run: |
          sleep 5
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://${TARGET_IP}/health/ready)

          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Verification passed: Service and DB are UP!"
          else
            echo "❌ Verification failed: HTTP Status $HTTP_STATUS"
            exit 1
          fi
